### ISSUE TITLE
Unable to install the bundle, composer error

### ISSUE THREAD

**Issue by marcodepolo** [wearejust/form-bundle#7]
## Subject

I'm porting a legacy project to Symfony 5 and was having issue using switchery with the form component. Googling around for solutions led me here, which I think is exactly what I need, unfortunately I think the repo might be getting a bit old for Symfony 5.

## Steps to reproduce

Setup Symfony 5 project
run install command :
/var/www/symfony # composer require wearejust/form-bundle "~0.1"

## Expected results

Bundle should be installed

## Actual results

/var/www/symfony # composer require wearejust/form-bundle "~0.1"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.1.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - wearejust/form-bundle 0.8.3 requires symfony/framework-bundle ~2.7|~3.0|~4.0 -> no matching package found.
    - wearejust/form-bundle 0.8.2 requires symfony/framework-bundle ~2.7|~3.0|~4.0 -> no matching package found.
    - wearejust/form-bundle 0.8.1 requires symfony/framework-bundle ~2.7|~3.0|~4.0 -> no matching package found.
    - wearejust/form-bundle 0.8 requires symfony/framework-bundle ~2.7|~3.0 -> no matching package found.
    - wearejust/form-bundle 0.7.1 requires symfony/framework-bundle ~2.7|~3.0 -> no matching package found.
    - wearejust/form-bundle 0.7 requires symfony/framework-bundle ~2.7|~3.0 -> no matching package found.
    - wearejust/form-bundle 0.6 requires symfony/framework-bundle ~2.7|~3.0 -> no matching package found.
    - wearejust/form-bundle 0.5 requires symfony/framework-bundle ~2.7|~3.0 -> no matching package found.
    - wearejust/form-bundle 0.4 requires symfony/framework-bundle ~2.7|~3.0 -> no matching package found.
    - wearejust/form-bundle 0.3 requires symfony/framework-bundle ~2.7|~3.0 -> no matching package found.
    - wearejust/form-bundle 0.2 requires symfony/framework-bundle ~2.7|~3.0 -> no matching package found.
    - wearejust/form-bundle 0.1.2 requires symfony/framework-bundle ~2.7|~3.0 -> no matching package found.
    - wearejust/form-bundle 0.1 requires symfony/framework-bundle ~2.7|~3.0 -> no matching package found.
    - Installation request for wearejust/form-bundle ~0.1 -> satisfiable by wearejust/form-bundle[0.1, 0.1.2, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.7.1, 0.8, 0.8.1, 0.8.2, 0.8.3].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by ceesvanegmond** [comment]
@marcodepolo Feel free to to PR!
